### ISSUE TITLE
Spike: Are analytics funnels possible with Google Tag Manager? 

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-google-analytics#17]
@iteles has asked for us to look into analaytics funnels in Google Tag Manager, this is a totally new topic for me! 

As such we are doing a short spike on:
- [x] what is an analytics funnel?
- [x] are they possible with Google Tag Manager?

EDIT: With this information now collated, we need to add this information to the README.md! As indicated by the `help wanted` label, it would be great if someone wanted to make a PR for this.

**Comment by ZooeyMiller** [comment]
On what is funnel analysis: 

> Funnel analysis involves using a series of events that lead towards a defined goal, like from user engagement in a mobile app to a sale in an eCommerce platform or advertisement to purchase in online advertising.[1] The funnel analyses "are an effective way to calculate conversion rates on specific user behaviors".[2] This can be in the form of a sale, registration, or other intended action from an audience. The origin of the term funnel analysis comes from the nature of a funnel where individuals will enter the funnel, yet only a small number of them will perform the intended goals.
> https://en.wikipedia.org/wiki/Funnel_analysis

It seems to be, defining a goal for a user, say going to a certain url, watching a video, submitting something, and tracking the path to that goal, and seeing where users stop. 

Say, for example you have a survey form you want a user to submit, and there are 3 pages leading up to the submission of the survey, your home page, a description of the survey, and then the survey itself (the final goal being the submission of the survey). Funnel analysis looks at how many users did achieve the overall goal, and for those users that did _not_ complete the overall goal, at what point did they stop? So if 100 users went to the home page, but only 50 users submitted the survey, at what point did those users leave? By doing this you can look into the things going on in the pages that the most users leave on, and analyse how you can change the things on the page to reduce the drop rate.

**Comment by ZooeyMiller** [comment]
It seems that for setting up funnels on Google Analytics you do not necessarily need to use GTM, with Google Analytics goals, you can set up a funnel and view the information about it.

This article is a good resource: https://blog.kissmetrics.com/conversion-funnel-survival-guide/

The video that accompanies the above article is also pretty helpful https://www.youtube.com/watch?v=6IzxqN0WLjM

## In order to set up a funnel

go to GTM dashboard, then click admin

![analytics - google chrome_030](https://user-images.githubusercontent.com/21139983/30964900-2bfc35f6-a44b-11e7-8c02-fe38c19a9c36.png)

then click on goals

![analytics - google chrome_031](https://user-images.githubusercontent.com/21139983/30964902-2bff5506-a44b-11e7-9a82-0c703cfa7c35.png)

click new goal

leave template selected

click continue, then give your goal a name, we'll go with "Get to done page", and we're going to select destination, as in we want the user to go to a certain page, but as you can see there are other goals available.

![analytics - google chrome_032](https://user-images.githubusercontent.com/21139983/30964898-2bf9c208-a44b-11e7-8b2e-8f83649d1da5.png)

next you're going to enter the endpoint for the page you want the user to get to, and the funnel of pages for the user to go thorugh to get there, as you can see in this image, our endpoint is "/GTM-practice/done" and the user will be starting on "/GTM-practice/index", then going to "/GTM-practice/first-step" and "/GTM-practice/second-step" before reaching "/GTM-practice/done"

![analytics - google chrome_035](https://user-images.githubusercontent.com/21139983/30964901-2bfe913e-a44b-11e7-91c4-5fb4d22ec14b.png)

Then click done!

in order to view your funnel visualisation go back to the dashboard, then click `Conversions`, `Goals`, and then `Funnel Visualisation`. It'll look something like this!

![goal funnel - analytics - google chrome_034](https://user-images.githubusercontent.com/21139983/30964903-2c43666a-a44b-11e7-829a-653c235a5e44.png)

We've just made this funnel so we will have to wait for a while for data to come through, to see if the data is coming through in real time you can click on the `Real-Time` tab, and then `Conversions` to see the goal being fulfilled in real time, this won't show your funnel visualisation though, you'll have to wait for that!

![conversions - analytics - google chrome_036](https://user-images.githubusercontent.com/21139983/30964899-2bfa4f8e-a44b-11e7-9924-4f9f77c6628f.png)

**Comment by iteles** [comment]
@ZooeyMiller I reckon we need to keep this open until it has been added to the readme 😊

**Comment by ZooeyMiller** [comment]
@iteles Apologies! I'll make it clear in the top comment that this is why the issue is open.
